// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.VisualStudio.Data.Sqlite
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSqliteDataPackageString = "0feac8da-2a45-4623-8179-2e5b82928098";
        public static Guid guidSqliteDataPackage = new Guid(guidSqliteDataPackageString);

        public const string guidSqliteDataPackageCmdSetString = "f851f287-fa5b-491f-922d-12bcc4a13af3";
        public static Guid guidSqliteDataPackageCmdSet = new Guid(guidSqliteDataPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InstallToolboxId = 0x0100;
    }
}