name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore dependencies
      run: MSBuild -t:Restore -p:Configuration=Release -m
    - name: Build
      run: MSBuild -p:Configuration=Release -m
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: 'VS.Data.Sqlite\\bin\\*\\VisualStudio.Data.Sqlite.vsix'
    - name: Test
      uses: microsoft/vstest-action@main
      with:
        testAssembly: '**\\VisualStudio.Data.Sqlite.IntegrationTests.dll'
        searchFolder: 'VS.Data.Sqlite.IntegrationTests\\bin\\'
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      env:
        APPVEYOR_REPO_PROVIDER: gitHub
        APPVEYOR_REPO_NAME: ${{ github.repository }}
        APPVEYOR_REPO_BRANCH: ${{ github.ref_name }}
      run: |
        (New-Object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
        Vsix-PublishToGallery VS.Data.Sqlite\bin\*\VisualStudio.Data.Sqlite.vsix
