name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore dependencies
        run: MSBuild -t:Restore -p:Configuration=Release -m
      - name: Build
        run: MSBuild -p:Configuration=Release -m
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: 'VS.Data.Sqlite\\bin\\*\\VisualStudio.Data.Sqlite.vsix'
      - name: Test
        run: '& "$(vswhere -property installationPath)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" **\bin\**\*test.dll **\bin\**\*tests.dll'
      - name: Publish
        if: ${{ github.repository_owner == 'bricelam' && github.event_name == 'push' }}
        env:
          APPVEYOR_REPO_PROVIDER: gitHub
          APPVEYOR_REPO_NAME: ${{ github.repository }}
          APPVEYOR_REPO_BRANCH: ${{ github.ref_name }}
        run: |
          (New-Object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
          Vsix-PublishToGallery VS.Data.Sqlite\bin\Release\VisualStudio.Data.Sqlite.vsix
